app/Http/Controllers/ItemController.php, resources/js/components/CommentListComponent.vue, resources/sass/components/timeline.scss, routes/web.php
closes #102 
Além de corrigir o espaçamento do primeiro comentário, esta PR remove a rota `items.store` que não estava mais sendo utilizada e corrige o alinhamento entre os botões de criar reação para item e para comentário.
=> fix: Fixes spacing for first comment

app/Document.php, app/Http/Controllers/API/DocumentController.php, app/Http/Resources/DocumentResource.php, config/filesystems.php, routes/api.php
colses #110 
Esta _issue_ cria uma estrutura básica para o CRUD de documentos.
Dado que são enviados arquivos, requisições devem obedecer o formato `multipart/form-data` (ou seja, utilizar o cabeçalho `'Content-Type': 'multipart/form-data'`). Para o método `PUT`, deverá ser utilizado um campo `_method=PUT`, utilizando o método `POST` para requisição, como [descrito na documentação](https://laravel.com/docs/8.x/blade#method-field).
=> feat(document): adds basic Document CRUD.

app/Http/Controllers/API/ItemController.php, app/Http/Controllers/ItemController.php, app/Http/Resources/FeedbackResource.php, app/Http/Resources/ServiceResource.php, resources/js/app.js, resources/js/components/admin/Services.vue, resources/js/components/feedbacks/Feedback.vue, resources/js/components/index/Feedbacks.vue, resources/js/components/items/ItemPage.vue
Algumas melhorias de UX/UI à serem feitas
- - [x]  Exibir o nome do solicitante
- - [x]  Exibir abaixo do titulo a categoria e localização do item
- - [x]  atualizar o `update_at` toda vez que for feito um comentário
- - [x]  Corrigir o ícone do github quando há um link da issue cadastrado, que não está diferenciando
- - [x]  Corrigir o campo categoria para aparecer o nome da categoria e não o id
- - [x]  Deve-se exibir também a especificação e localização do serviço solicitado
=> melhorias de UX/UI

resources/js/pages/EditPage.vue
fix: #310 
Depois de concluir a edição do item, ele redireciona para a aba anterior, podendo ser "Admin" ou Acompanhar Serviços
=> fix(redirect to admin page when edit)

app/Http/Controllers/API/ServiceController.php, app/Http/Resources/ServiceResource.php, app/Item.php, database/migrations/2020_07_06_185039_create_items_table.php, resources/js/components/admin/Services.vue, resources/js/components/servicos/MyServices.vue, resources/js/components/servicos/ServiceForm.vue, resources/js/pages/EditPage.vue, resources/js/pages/ItemPage.vue
fix: #305 
Foi adicionado o **delivery_date** nos formulários de solicitação, de edição. Algumas coisas visuais foram alteradas para conseguir adicionar a data de entrega:
- As caixas de serviço da aba de "Acompanhar Serviços"
- As caixas de serviço da aba de "Admin"
- A página de edição de serviços
- Página de acompanhamento de serviço
A data de entrega foi limitada atravéz do min dentro do input date e também foi feito uma validação dentro do próprio formulário caso o "min" seja removido via ferramentas de desenvolvedor.
A mesma coisa foi feita na aba de edição, porém, utilizando a data de criação como referência dos 10 dias, e não o dia atual.
**obs:** Também tive que atualizar a migration do item, para adicionar o delivery_date
=> feat(add delivery date on services)

app/Channels.php, app/User.php, database/migrations/2021_07_08_111924_create_channels_table.php
Nessa issue foi criado um modelo "Channels" que contem user_id e fcm_token. O user id é um FK one-to-one que vai ligar cada usuário à um dispositivo com fcm_token. Esse token será utilizado para envio de notificações para os dispositivos movéis.
fix: #340
=> add: Channels model

app/Channels.php, app/Http/Controllers/API/ItemController.php, app/Http/Controllers/API/ServiceController.php, app/Notifications/PushNotification.php, app/User.php, composer.json, composer.lock, config/firebase.php, database/migrations/2021_07_08_111924_create_channels_table.php
Nessa issue foi criado um método onde podemos enviar notificação (push notification) para os usuários do Practice caso ela possua um login realizado pelo app. A ideia é que seja implementado um método de salvar token usando as rotas da issue #341 para cadastrar o dispositivo do usuário na nossa API. Assim, caso haja uma modificação de estado em uma solicitação feita pelo usuário em específico ou seja adicionado um comentário, se houver um `fcm_token` o dispositivo receberá uma notificação.
OBS: Para que o envio de notificação funcione, é preciso adicionar informações do Firebase na pasta .env
Para isso, faça o seguinte:
- vá nas configurações do serviço web da sua conta FireBase.
- Acesse a aba "Contas de Serviço"
- Clique em gerar nova chave privada
- Copie as informações encontradas no …
=> Feat: create sending push notifications method

app/Http/Controllers/API/ItemController.php, app/Http/Controllers/API/ServiceController.php
O erro no envio do E-mail de notificação quando houvesse algum comentário ou alteração no serviço estava impedindo que a Push Notification fosse enviada. Os dois estavam no mesmo Try Catch e quando dava o erro no envio do e-mail, ele acabava pulando pro catch e não realizava o envio da notificação.
Nessa issue, apenas separei as notificações de e-mail e do app em dois try/catchs para resolver esse problema e criei um try/catch para a solicitação de um novo serviço pois estava dando erro na solicitação justamente por causa do erro do e-mail.
Fix: #353
=> fix: PushNotification without e-mail send

README.md
Adicionei algumas informações básicas sobre como gerar e adicionar as credenciais do Google para que a integração funcione. 
Fix: #403
=> feat: informações sobre o google credentials ao readme

app/Http/Livewire/Order/Create.php
Adicionei a possibilidade de criar perguntas adicionais não obrigatórias. Para não gerar problema com as questões já criadas anteriormente quando não for especificado se a pergunta é obrigatória ela é marcada como obrigatória por padrão.
Para marcar uma pergunta como não obrigatória basta usar a sintaxe `{"required": "false" }` antes da pergunta:
```
{"required": "false"} Sua pergunta aqui
{"type": "file", "required": "false"} Adicione o arquivo aqui
```
Quando uma pergunta não obrigatoria não é respondida eu anexei a mensagem "Pergunta não respondida pelo solicitante" como resposta para não gerar problema nas páginas que exibem as solicitações.
Também removi o css que não permitia copiar links das labels das perguntas e corrigi um problema que fazia não ser possível ler a resposta …
=> feat: permite criar perguntas não obrigatórias

.env.example, app/Broadcasting/PushNotificationChannel.php, app/Http/Livewire/Comments.php, app/Notifications/OrderCommented.php, app/Notifications/OrderCompleted.php, app/Notifications/OrderCreated.php, app/Notifications/OrderNeedsReview.php, app/Notifications/OrderStarted.php
Utilizei a mesma estrutura que é usada para o envio de email, então agora além de enviar o email também será enviada uma push notification caso a pessoa tenha o aplicativo instalado. Tentei manter as mensagens enviadas parecidas com as do email, mas é possível alterar o conteúdo da notificação facilmente. Também notei que ao comentar o evento de notificação estava sendo disparado duas vezes, então corrigi isso também.
Como eu precisava do jwt token para acessar a rota da api eu gerei um token compatível para o usuário que vai receber a notificação na função que vai disparar o envio da mesma e utilizei ele para fazer a request para a api. 
Fix: #374
=> feat: adiciona push notifications pela API central

resources/views/order/list.blade.php
A tela de acompanhamento de pedidos era bem pouco responsiva e apresentava dificuldades de uso em vários os tamanhos, então eu ajustei o layout para um conjunto maior de tamanhos.
**Mobile:**
**Tamanho médio:**
**Desktop:**
Fix: #440
=> fix: corrige os problemas do layout da tela de acompanhamento de pedidos

resources/views/livewire/comments/main.blade.php
Fix: #401 
Conforme tarefa antiga.
Verifiquei que as tags para markdown estavam funcionando.
Porém, a quebra de linha não estava refletindo nos comentários.
Adicionei o nl2br na hora de listar os comentários. Essa função identifica e mostra as quebras de linha.
=> feat: adicionado quebra de linha nos comentários #401

app/Http/Controllers/API/GithubWebhookController.php, app/Services/Github.php
Pra conseguir testar, precisa disponibilizar o servidor (localhost) na internet, pois o webhooks do github fará requisições.
Também é necessário ajustar as configurações de wehook do playground para o link de host que foi criado.
Podemos testar a funcionalidade aqui: https://2071-2804-f40-309-9b01-88f0-98ee-23c9-576e.sa.ngrok.io (deixarei rodando por um tempo)
A ideia é usar as tags `mural:<alguma_coisa>` pra alterar os estados diretamente no mural. Ao adicionar uma tag desse tipo, as demais desse tipo são removidas e o mural é atualizado com a tag selecionada.
Como ele altera apenas no banco de dados, é necessário dar `f5` no mural.
Fix: #470
=> feat: cria tratamento para adição de labels relacionadas ao status do pedido no mural

resources/views/livewire/crud/change.blade.php, resources/views/livewire/crud/main.blade.php, resources/views/livewire/order/show.blade.php, resources/views/order/create.blade.php
Agora o formulário de edição respeita o tamanho do aparelho:
Além disso também ajustei a tela de solicitar serviço para que o formulário ocupasse mais espaço na tela de aparelhos menores.
Fix: #486
=> fix: ui\ux adjustments

app/Http/Livewire/Order/Show.php
Apenas fiz uma verificação antes do método para checar se o link do git está nulo ou não.
Fix: #489
=> fix: Erro quando link do git é nulo

app/Http/Controllers/API/GithubWebhookController.php, app/Http/Livewire/Order/Show.php, app/Services/Github.php
Nesta issue, foi adicionado uma feature quando você linka uma issue com o pedido. No mural, quando você adicionar o link da issue, o bot irá adicionar a mensagem de vínculo de pastas do Google drive.
Fix: #495
=> feat: Adiciona fluxo de pastas ao adicionar link no pedido 

resources/views/livewire/crud/success.blade.php
Nessa issue, apenas alterei o design do balão de confirmação ao criar um pedido.
Antes:
---
Depois:
Fix: #499
=> fix: ajusta design da mensagem de sucesso

app/Models/Order.php
Nesta issue apenas precisei pesquisar como funciona a validação de data no laravel.
Utilizei um `after:date` na validação, porém tive que definir uma outra váriavel pra ser a "NOW_PLUS_FEW_DAYS" só que um dia anterior pra servir de validação, pois ele não utiliza um mínimo mas sim uma data depois do valor inserido.
Fix: #506
=> fix: date validation

resources/views/livewire/admin/orders.blade.php
Foi adicionado uma alteração no path para montar a paginação e evitar o erro de redirecionamento das páginas.
=> fix: #525 orders pagination error

app/Http/Livewire/Admin/Orders.php, resources/views/livewire/admin/orders.blade.php
foi criado um filtro por meio de pesquisa na página de pedidos onde consegue procurar pelo título dos pedidos 
alteração feita dentro da função findOrders() no componente Livewire de Orders, adicionada uma verificação caso exista algo na barra de pesquisa no front, esse valor é recebido pra montar a query no componente e realizar a consulta de acordo com a pesquisa. também adicionado uma verificação caso existam valores nos outros filtros dropdown para funcionar simultaneamente, mas sempre que houver filtros não há paginação para não ocorrer erros.
=> feat: #547 filtro de pesquisa na página de pedidos
