practice-uffs/mural

README.md, src/package-lock.json, src/package.json
- Foi adicionado no _readme_ os passos para configuração e execução do projeto;
- Fez-se uma síntese sobre a descrição do projeto baseado no que o @Dovyski nos passou no telegram (ela deve ser melhorada futuramente);
- O texto sobre a descrição das features ainda é o do template pois ainda não tem-se uma muito ideia clara;
- closes #1;
- OBS:  verificar se a descrição do projeto está condizente;
=> docs(readme): adds running steps and project description

src/app/Http/Controllers/ItemController.php, src/database/migrations/2020_07_06_180509_create_locations_table.php, src/database/migrations/2020_07_06_180510_create_categories_table.php, src/database/migrations/2020_07_06_185039_create_items_table.php, src/resources/views/item/create.blade.php, src/resources/views/item/edit.blade.php, src/routes/web.php
closes #11
O controller foi alterado conforme descrito em #11.
O banco de dados foi alterado: campos do tipo `text` antes definidos como `->default('')`, foram alterados para `->nullable()`, devido à erros que ocorreram.
Um formulário (um novo arquivo) para a rota `items.create` foi criado (é apenas uma cópia do furmulário da rota `items.edit`).
=> Altera o controller "ItemController"

src/database/seeds/CategorySeeder.php, src/database/seeds/DatabaseSeeder.php, src/database/seeds/LocationSeeder.php
closes #31 
Adiciona *seeders* para categoria e para local. Deve-se executar `php artisan db:seed` para executá-los.
=> feat: Adds location and category db seeders.

src/resources/js/app.js, src/resources/sass/_custom-variables.scss, src/resources/sass/app.scss, src/resources/sass/components/card.scss, src/resources/sass/components/navbar.scss, src/resources/views/item/create.blade.php
closes #23
Há um bug no switcher visto do mobile, será removido posteriormente.
=> refactor: Refactor items.create view

src/app/Http/Controllers/ItemController.php, src/resources/views/item/create.blade.php, src/resources/views/item/edit.blade.php, src/resources/views/item/show.blade.php
=> feat(items): create items.edit view

src/database/migrations/2014_10_12_000000_create_users_table.php, src/database/migrations/2020_07_06_180509_create_locations_table.php, src/database/migrations/2020_07_06_180510_create_categories_table.php, src/database/migrations/2020_07_06_185039_create_items_table.php, src/database/migrations/2020_07_06_195010_create_reactions_table.php
=> fix: Fix ids' format.

src/app/Helpers/HomerConfigHelper.php
closes #16
A issue n é totalmente resolvida, pois as estilizações requeridas não podem ser facilmente alcançadas utilizando o HOMER, portanto a dashboard será redefinida, conforme issue #49
=> feat: adds creation buttons.

src/app/Http/Controllers/API/ReactionController.php, src/app/Http/Resources/ReactionResource.php, src/public/css/app.css, src/public/js/app.js, src/resources/js/app.js, src/resources/js/components/ReactionListComponent.vue, src/resources/sass/components/reaction.scss
=> fix(items): fixes visual bugs on reaction list

src/resources/js/app.js, src/resources/sass/app.scss, src/resources/sass/components/header.scss, src/resources/views/item/create.blade.php, src/resources/views/item/edit.blade.php, src/resources/views/item/show.blade.php
=> feat(header): make a new header

src/resources/js/components/CommentListComponent.vue, src/resources/sass/components/timeline.scss
=> feat(comment): fix comment list visual bugs.

src/resources/js/components/CommentListComponent.vue, src/resources/js/components/ReactionListComponent.vue
Adiciona reações nos comentários.
=> feat(reactions): Add reactions to comments.

src/app/Http/Controllers/ItemController.php, src/config/app.php, src/resources/lang/pt/validation.php, src/resources/sass/app.scss, src/resources/views/item/create.blade.php
- Implementa o `/service/create`;
- Adiciona o arquivo que traduz as mensagens de erro;
=> feat: implements service create

src/app/Http/Controllers/API/ItemController.php
closes #4
(Ouve um erro na hora de criar o *branch*, deveria ser 4 mas está 21).
Deverá ser criada uma *API reference* para facilitar o uso das demais aplicações.
=> feat: Add api endpoint for Item.

src/app/Category.php, src/app/Http/Controllers/API/ConfigController.php, src/app/Http/Controllers/ItemController.php, src/app/Item.php, src/database/migrations/2020_07_06_180510_create_categories_table.php, src/database/seeds/CategorySeeder.php
closes #65 
(novamente, houve um erro na criação da branch, deveria ser 65 e não 21. Sorry)
=> chore: change category model

app/Http/Controllers/ItemController.php, resources/sass/components/header.scss, resources/views/item/edit.blade.php
=> fix: corrige problema com campo 'hidden'

app/Http/Controllers/ItemController.php, resources/js/components/CommentListComponent.vue, resources/js/components/ReactionListComponent.vue, resources/sass/components/header.scss, resources/sass/components/timeline.scss, resources/views/item/index.blade.php, resources/views/item/show.blade.php
closes #49
Essencialmente, esta PR adiciona um "toggle" entre lista e grid, na _index_ dos itens. As demais modificações foram atendidas na PR #81.
=> feat: replaces HOMER with "hand-crafted" dashboard

resources/js/app.js, resources/js/components/FeedbackFormComponent.vue, resources/js/components/ServiceFormComponent.vue, resources/js/components/base/Modal.vue, resources/sass/_utilities.scss, resources/views/item/index.blade.php
- Essas alterações refatoram o modal de criação de um serviço para que ele passe a usar o modal base;
=> refactor(service): implements service creation using base modal

app/Item.php, resources/js/components/FeedbackFormComponent.vue, resources/sass/components/card.scss, resources/sass/components/header.scss, resources/sass/components/navbar.scss, resources/views/item/index.blade.php, resources/views/layouts/headerAuth.blade.php
- Essas alterações incluem informações sobre o autor do feedback e as reações na listagem de ideias;
- Não foi implementado na listagem de serviços por que ela não foi implementada ainda, mas como dito na _issue_ a implementação será praticamente a mesma;
- Abaixo está o card com as novas alterações (qualquer sugestão é bem-vinda);
- closes #95;
=> feat(feedback): includes author info and reactions in the feedback list

resources/js/components/ItemListComponent.vue, resources/js/components/ServiceFormComponent.vue, resources/sass/app.scss, resources/sass/components/modal.scss, resources/sass/components/navbar.scss, resources/views/layouts/header.blade.php
Considerações:
- Essas alterações resolvem o problema de posicionamento bagunçado quando os cards tem alturas diferentes (o que a gente viu [aqui](https://github.com/practice-uffs/web-feedback/pull/105#pullrequestreview-479208684)), e ajusta uns detalhes nos estilos que irei comentar a seguir;
- Esse pr não resolve nenhuma _issue_ em específico;
- Fiz na branch 95 pois foi na review dessa _issue_ que o bug foi encontrado (não achei necessário abrir uma _issue_ especificamente pra isso);
=> fix: adjust list items

.github/workflows/deploy-qa.yml
Esse PR automatiza o deploy do web-feedback no ambiente de teste/QA disponível em [qa.mural.practice.uffs.cc](http://qa.mural.practice.uffs.cc). Acho que não tem muito para ser revisado nesse PR, a não ser garantir que ele funciona =P
Fix: #120
=> chore(ci): add github action to automate deploy in QA

app/Document.php, app/Item.php, database/migrations/2020_09_12_225300_create_documents_table.php
closes #109
Esta PR cria o _model_ e a _migration_. Configurações adicionais referentes ao `storage` serão adicionados na resolução da issue #110.
=> feat: creates 'Document' model

resources/js/components/base/Modal.vue, resources/js/components/items/FeedbackForm.vue, resources/js/components/items/ServiceForm.vue
- Implementação de exibir as mensagens de validação foram feitas no modal mais geral;
- Caso o formulário não for válido as mensagens são exibidas no _footer_ do modal e este não é fechado;
- Caso houver problemas com as informações e o modal for fechado e em seguida reaberto as mensagens continuarão lá;  
- closes #118;
**OBS**: os comentários a seguir fazem considerações mais específicas em relação ao que foi implementado.
=> feat(itens): adds validation messages

resources/js/components/index/Feedbacks.vue, resources/js/components/index/Services.vue, resources/js/components/layouts/FooterComponent.vue, resources/js/components/layouts/HeaderComponent.vue, resources/js/components/layouts/Nuvens.vue, resources/views/index.blade.php
Corrigido alguns detalhes de responsividade e os erros no textos apontados pelo @lcaimi na issue [65](https://github.com/practice-uffs/website-programa/issues/65)
=> Correções na responsividade e texto

app/Http/Controllers/FeedbackController.php, public/js/app.js, resources/js/app.js, resources/js/components/feedbacks/Feedback.vue, resources/js/components/feedbacks/FeedbackList.vue, resources/js/components/feedbacks/FeedbackPage.vue, resources/views/pages/feedbacks.blade.php
implementação inicial da pagina feedback #129, ainda falta o modal com o POST de novos feedbacks
=> implementação inicial da pagina feedback #129

package-lock.json, package.json, public/js/app.js, resources/js/app.js, resources/js/components/feedbacks/FeedbackForm.vue, resources/js/components/feedbacks/FeedbackModal.vue, resources/js/components/feedbacks/FeedbackPage.vue, resources/views/layouts/base.blade.php, resources/views/pages/feedbacks.blade.php
=> Finalização issue #129

.github/workflows/deploy-qa.yml, .github/workflows/deploy.yml
Espero que isso resolva o problema de deploy em produção e QA. Ele limpa a pasta de trabalho antes de fazer qualquer compilação. Além disso, remove seeding para evitar erros com duplicação.
=> fix(ci) ajusta action para deploy para evitar problema com npm build

package-lock.json, package.json, public/css/app.css
Esse PR apenas atualiza os pacotes JS para versões mais recentes.
=> chore(js) atualiza pacotes para melhorar action de deploy

.github/workflows/ci-uffs-cc.yml, README.md, app/Http/Controllers/API/AuthController.php, app/Http/Controllers/Auth/LoginController.php, app/Http/Kernel.php, app/Http/Middleware/ApiProtectedRoute.php, app/User.php, composer.json, composer.lock, config/app.php, config/auth.php, config/jwt.php, database/migrations/2020_11_30_185725_add_password_user.php, public/css/app.css, routes/api.php
foi implementado a validação dos endpoints utilizando [JWT](https://jwt-auth.readthedocs.io/)
=> alterações dos enpoints para validar com os token #170

app/Http/Controllers/API/AuthController.php
Mudado a regra de negócio do login para não salvar a senha do usuário idUFFS no sistema e manter a senha interna do Weebfeedback como o `pessoa_id` que é retornado pela confirmação do usuário pela base idUFFS.
=> (refactor):regra de negocio do login #170

app/Http/Controllers/API/GithubWebhookController.php, app/Http/Resources/GithubWebhookResource.php, routes/api.php, routes/web.php
Para o funcionamento do Webhook o usuário dono do projeto (@Dovyski) tem de colocar a URL no serviço de webhook e ela tem que ser: `{{URL}}/webhook/github/comment`
Depois restringir o serviço de webhooks apenas para comentários em issues
Esse endpoint tratará especificamente de CRUD pra os comentários nas issues. Para futuras integrações outros endpoints serão criados.
=> Criado Webhook de integração com github

app/Http/Controllers/API/GithubWebhookController.php, resources/js/components/items/CommentList.vue
Comentários do github só vão para o webfeedback caso tenham a tag `#cliente `
=> Filtro comment webfeedback

app/Http/Controllers/API/ItemController.php, resources/js/components/items/CommentList.vue, resources/js/pages/ItemPage.vue
Resolvido o bug com o comentários com #cliente nos feedbacks e feito o live reload, para add o comentário na listage sem a necessidade de recarregar a página
=> fix comentário com #cliente #223

.github/workflows/ci-uffs-cc.yml, config/app.php, config/laravel-subscribers.php, resources/views/components/newsletter.blade.php, resources/views/newsletter/subscribed.blade.php, routes/web.php
Depois da inscrição, mostra uma mensagem bonita agora:
=> Melhora a UX de inscrição na newsletter

resources/js/components/items/CommentList.vue, tests/TestCase.php
(Style): arruma quebra de linha comment
=> (Style): arruma quebra de linha comment

app/Http/Controllers/API/ItemController.php, resources/js/components/items/CommentList.vue, routes/api.php
Adiciona opção para excluir um comentário.
Fix: #291
=> feat(comment): adiciona opção para excluir um comentário

resources/js/components/admin/Services.vue, resources/js/components/items/CommentList.vue, resources/js/components/servicos/MyServiceLists.vue, resources/js/components/servicos/MyServices.vue, resources/js/pages/AdminPage.vue, resources/js/pages/ItemPage.vue
Issue #320, adicionei o nome da última pessoa a ter comentado como foi solicitado (espero que esteja tudo certo, qualquer coisa só chamar):
=> Add informações da ultima pessoa a ter comentado na solicitação #320

resources/js/components/servicos/ServiceLists.vue
=> refactor: Modifica o layout da página de Solicitar Serviços

resources/js/components/servicos/MyServiceLists.vue
one more verification on array of services.
Apenas adicionei mais uma verificação no if para que o usuário tenha apenas suas solicitação na página de "Acompanhar Serviços" - MyServiceList.vue, linha 67, 69, 71 e 73.
fix: #306
=> fix(service view filter)

resources/js/app.js, resources/js/components/servicos/MyServices.vue, resources/js/pages/ItemPage.vue
=> feat: adiciona tag que indica o status da solicitação

app/Channels.php, app/Http/Controllers/API/ChannelsController.php, app/User.php, database/migrations/2021_07_08_111924_create_channels_table.php, routes/api.php
Nessa issue, foram criadas as rotas que serão utilizadas pelo app para setar e remover os tokens dos dispositivos que serão vinculados aos usuários do mural.
Rotas criadas:
fix: #341
=> create: endpoints post, patch and delete to Model Channel

app/Models/Order.php
Verificação fazia cair sempre no doing se houvesse link do github vinculado.
Fix: #419
=> Fix: Erro no Status de solicitação

public/css/theme.css, resources/views/layouts/header.blade.php, resources/views/login.blade.php
Nesta issue, foi ajustado a logo na tela de login do mural.
Fix: #451
=> Fix: ajusta logo e dropdown

resources/views/components/servicos.blade.php, resources/views/index.blade.php
Nesta issue, apenas foi ajustado algumas questões de layout que estavam causando sobreposições na tela inicial na versão mobile.
Fix: #456
=> fix: ajusta layout da tela inicial

app/Http/Livewire/Comments.php, app/Http/Livewire/Crud/Main.php, app/Providers/AppServiceProvider.php, public/css/theme.css, resources/views/livewire/comments/main.blade.php, resources/views/livewire/crud/main.blade.php
Nesta issue, foi ajustado o pagination para que não fique escrito apenas "pagination.next" no mobile.
Foi alterado o pagination para o bootstrap.
Fix: #459
=> fix: Ajusta pagination

resources/views/livewire/order/show.blade.php
Demorei um pouco pra entender o que estava acontecendo, porém percebi que os valores salvos no banco de dados continham as quebras de linha, então percebi que só precisava ajustar a forma como as descrições eram mostradas na view.
Fix: #491
=> fix: quebra de linha na descrição de um pedido

app/Http/Controllers/API/GithubWebhookController.php
Nessa issue, adicionei uma forma de vincular as pastas do drive mesmo depois de criar uma issue.
Para testar, basta criar um comentário assim:
`mural: <link>`
Podem utilizar o mural que está rodando no meu localhost pra testar: https://3767-2804-f40-309-9b01-ef03-68b0-8fff-4df.sa.ngrok.io/servico/16
---
=> feat: vinculo de pastas usando comentário

app/Http/Livewire/Order/Show.php
Apenas adicionei a barra que estava faltando no link que o bot comenta na issue.
Fix: #513
=> fix: add barra ao inserir link da solicitação

public/css/ideas.css, resources/views/ideas.blade.php, resources/views/layouts/base.blade.php, resources/views/livewire/crud/change.blade.php
Alteração na página de Ideias para melhor responsividade no mobile.
Fix: #467
=> fix: ajustes de layout

public/css/theme.css, resources/views/layouts/base.blade.php
Ajustei o comportamento para o botão de abrir o widget; 
fix: #516
=> New: estilo do botão

app/Exports/UsersExport.php, app/Http/Controllers/Admin/UserController.php, composer.json, composer.lock, resources/views/livewire/crud/main.blade.php, routes/web.php
Foi adicionado um botão na parte superior direita da listagem de usuários, que, ao clicar, filtra os usuários normais do sistema e faz um download da lista de e-mails.
Exempo de arquivo obtido com 1 usuário:
=> Botão download e-mails #521

resources/views/admin/orders.blade.php, resources/views/feedbacks.blade.php, resources/views/ideas.blade.php, resources/views/layouts/base.blade.php
Foram removidas as margens dos arquivos das páginas internas e adicionado no arquivo base.blade.php para padronizar as páginas.
=> fix: #525 ajustada margem do topo das páginas

public/css/theme.css, resources/views/layouts/base.blade.php
Foi adicionado um botão de whatsapp para usuários logados, que abre uma nova aba e possibilita uma conversa com o número do PRACTICE.
=> feat: #528 adicionado botão de whatsapp p/ usuários logados

resources/views/livewire/crud/change.blade.php
=> feat: #536 adicionado referência sobre prazo de solicitação de serviço

app/Models/Order.php, database/migrations/2023_02_07_142054_add_wppnumber_to_orders_table.php, public/css/theme.css, resources/views/layouts/base.blade.php, resources/views/livewire/crud/change.blade.php, resources/views/livewire/order/show.blade.php
Foi adicionado o campo de contato para quem solicita um serviço. Com isso, essa nova informação de contato aparece também ao acompanhar um serviço, sendo possível contatar pelo whatsapp do solicitante com um clique.
=> feat: #529 adicionado campo contato na solicitação de um serviço

public/css/theme.css, resources/views/layouts/footer.blade.php
Foi adicionado um popup com a explicação de como é feita a utilização dos dados para solicitar o aceite dos termos.
O popup para de aparecer após o aceite.
=> fix: #532 adicionando popup consentimento de dados
